# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Chula Expo 2017' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  # Pods for Chula Expo 2017
  pod 'Alamofire', '~> 4.3'
end
